services:
  ha-fusion-pro:
    container_name: ha-fusion-pro
    build: .
    volumes:
      - ./data:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: Europe/Yekaterinburg
      HASS_URL: http://192.168.100.150:8123
    restart: always
# cd ~/Developer/ha-fusion && docker-compose -f compose-dev.yml up -d --build ha-fusion
