services:
  ha-fusion:
    container_name: ha-fusion-pro
    image: ghcr.io/bzzim/ha-fusion-pro
    volumes:
      - ./data:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: Europe/Yekaterinburg
      HASS_URL: http://192.168.100.150:8123
    restart: always
